#!/usr/bin/env python3
"""Generate the glyph preview index.html from SVG assets.

Run from the repository root or from this directory:

    python3 crates/drawify-core/src/icons/assets/glyphs/generate_index.py

The generated page inlines SVGs intentionally so currentColor previews, theme
switching, and tone switching behave the same way as the renderer.
"""

from __future__ import annotations

from html import escape
from pathlib import Path


ROOT = Path(__file__).resolve().parent
OUTPUT = ROOT / "index.html"
CATEGORY_ORDER = ["people", "databases", "messaging", "services", "cloud", "generic"]


def inline_svg(path: Path) -> str:
    svg = path.read_text(encoding="utf-8").strip()
    if svg.startswith("<svg ") and "aria-hidden" not in svg:
        svg = svg.replace("<svg ", '<svg aria-hidden="true" focusable="false" ', 1)
    return svg


def collect_svg_files() -> list[Path]:
    return sorted(ROOT.glob("**/*.svg"), key=lambda path: (path.parent.name, path.stem))


def grouped_svg_files(svg_files: list[Path]) -> list[tuple[str, list[Path]]]:
    groups: dict[str, list[Path]] = {}
    for path in svg_files:
        groups.setdefault(path.parent.name, []).append(path)

    ordered = [(category, groups.pop(category)) for category in CATEGORY_ORDER if category in groups]
    ordered.extend(sorted(groups.items()))
    return ordered


def render_card(path: Path) -> str:
    rel_path = path.relative_to(ROOT).as_posix()
    icon_id = path.stem
    return f'''        <article class="icon-card" data-id="{escape(icon_id)}" data-category="{escape(path.parent.name)}" data-path="{escape(rel_path)}">
          <div class="preview">{inline_svg(path)}</div>
          <div class="meta">
            <strong>{escape(icon_id)}</strong>
            <code>{escape(rel_path)}</code>
          </div>
        </article>'''


def render_section(category: str, files: list[Path]) -> str:
    cards = "\n".join(render_card(path) for path in files)
    return f'''    <section class="category" data-category="{escape(category)}">
      <div class="category-heading">
        <h2>{escape(category)}</h2>
        <span>{len(files)} icons</span>
      </div>
      <div class="grid">
{cards}
      </div>
    </section>'''


def render_html(svg_files: list[Path]) -> str:
    sections = "\n".join(
        render_section(category, files) for category, files in grouped_svg_files(svg_files)
    )
    total = len(svg_files)
    return f'''<!doctype html>
<!-- Generated by generate_index.py; do not edit index.html by hand. -->
<html lang="zh-CN">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Drawify Glyph Library</title>
  <style>
    :root {{
      color-scheme: light dark;
      --bg: #f7f7f5;
      --panel: #ffffff;
      --text: #202124;
      --muted: #6b7280;
      --line: #e5e7eb;
      --accent: #2563eb;
      --preview: #f1f5f9;
      --glyph-color: #111827;
      --shadow: 0 12px 30px rgba(15, 23, 42, 0.08);
    }}

    [data-theme="dark"] {{
      --bg: #0f172a;
      --panel: #111827;
      --text: #f8fafc;
      --muted: #94a3b8;
      --line: #243244;
      --accent: #60a5fa;
      --preview: #172033;
      --glyph-color: #f8fafc;
      --shadow: 0 12px 30px rgba(0, 0, 0, 0.28);
    }}

    [data-tone="blue"] {{ --glyph-color: #2563eb; }}
    [data-tone="green"] {{ --glyph-color: #15803d; }}
    [data-tone="orange"] {{ --glyph-color: #c2410c; }}
    [data-tone="purple"] {{ --glyph-color: #7c3aed; }}

    * {{ box-sizing: border-box; }}

    body {{
      margin: 0;
      min-height: 100vh;
      background: var(--bg);
      color: var(--text);
      font: 14px/1.5 ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    }}

    header {{
      position: sticky;
      top: 0;
      z-index: 10;
      padding: 20px clamp(18px, 4vw, 44px);
      border-bottom: 1px solid var(--line);
      background: color-mix(in srgb, var(--bg) 88%, transparent);
      backdrop-filter: blur(16px);
    }}

    .title-row {{
      display: flex;
      align-items: flex-end;
      justify-content: space-between;
      gap: 20px;
      margin-bottom: 16px;
    }}

    h1 {{
      margin: 0;
      font-size: clamp(24px, 4vw, 36px);
      letter-spacing: -0.04em;
    }}

    .summary {{ color: var(--muted); }}

    .toolbar {{
      display: flex;
      flex-wrap: wrap;
      gap: 10px;
      align-items: center;
    }}

    input[type="search"] {{
      width: min(420px, 100%);
      flex: 1 1 260px;
      border: 1px solid var(--line);
      border-radius: 12px;
      padding: 10px 12px;
      background: var(--panel);
      color: var(--text);
      outline: none;
    }}

    input[type="search"]:focus {{ border-color: var(--accent); }}

    button {{
      border: 1px solid var(--line);
      border-radius: 999px;
      padding: 9px 13px;
      background: var(--panel);
      color: var(--text);
      cursor: pointer;
    }}

    button:hover {{ border-color: var(--accent); }}

    .tone {{
      width: 34px;
      height: 34px;
      padding: 0;
      border-radius: 50%;
    }}

    .tone[data-color="default"] {{ background: #111827; }}
    .tone[data-color="blue"] {{ background: #2563eb; }}
    .tone[data-color="green"] {{ background: #15803d; }}
    .tone[data-color="orange"] {{ background: #c2410c; }}
    .tone[data-color="purple"] {{ background: #7c3aed; }}

    main {{ padding: 28px clamp(18px, 4vw, 44px) 60px; }}

    .category {{ margin-bottom: 34px; }}

    .category-heading {{
      display: flex;
      align-items: baseline;
      justify-content: space-between;
      margin-bottom: 12px;
    }}

    h2 {{
      margin: 0;
      font-size: 18px;
      text-transform: capitalize;
    }}

    .category-heading span {{ color: var(--muted); }}

    .grid {{
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(160px, 1fr));
      gap: 14px;
    }}

    .icon-card {{
      overflow: hidden;
      border: 1px solid var(--line);
      border-radius: 16px;
      background: var(--panel);
      box-shadow: var(--shadow);
    }}

    .preview {{
      display: grid;
      place-items: center;
      min-height: 116px;
      background: var(--preview);
      color: var(--glyph-color);
    }}

    .preview svg {{
      width: 48px;
      height: 48px;
      color: var(--glyph-color);
      overflow: visible;
    }}

    .meta {{ padding: 11px 12px 13px; }}

    .meta strong {{
      display: block;
      margin-bottom: 3px;
      font-size: 14px;
    }}

    code {{
      color: var(--muted);
      font: 12px/1.4 ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", monospace;
      word-break: break-all;
    }}

    .hidden {{ display: none; }}
  </style>
</head>
<body>
  <header>
    <div class="title-row">
      <div>
        <h1>Drawify Glyph Library</h1>
        <div class="summary"><span id="visibleCount">{total}</span> / {total} icons · grouped by asset folder</div>
      </div>
      <button id="themeToggle" type="button">切换深色</button>
    </div>
    <div class="toolbar">
      <input id="search" type="search" placeholder="搜索 id、分类或路径，例如 nginx / database / cloud" autocomplete="off" />
      <button class="tone" data-color="default" type="button" title="Default"></button>
      <button class="tone" data-color="blue" type="button" title="Blue"></button>
      <button class="tone" data-color="green" type="button" title="Green"></button>
      <button class="tone" data-color="orange" type="button" title="Orange"></button>
      <button class="tone" data-color="purple" type="button" title="Purple"></button>
    </div>
  </header>

  <main>
{sections}
  </main>

  <script>
    const root = document.documentElement;
    const search = document.getElementById('search');
    const visibleCount = document.getElementById('visibleCount');
    const cards = Array.from(document.querySelectorAll('.icon-card'));
    const categories = Array.from(document.querySelectorAll('.category'));

    document.getElementById('themeToggle').addEventListener('click', () => {{
      const isDark = root.dataset.theme === 'dark';
      root.dataset.theme = isDark ? '' : 'dark';
    }});

    document.querySelectorAll('.tone').forEach((button) => {{
      button.addEventListener('click', () => {{
        const color = button.dataset.color;
        if (color === 'default') {{
          delete root.dataset.tone;
        }} else {{
          root.dataset.tone = color;
        }}
      }});
    }});

    function applyFilter() {{
      const query = search.value.trim().toLowerCase();
      let visible = 0;

      cards.forEach((card) => {{
        const haystack = `${{card.dataset.id}} ${{card.dataset.category}} ${{card.dataset.path}}`.toLowerCase();
        const matched = !query || haystack.includes(query);
        card.classList.toggle('hidden', !matched);
        if (matched) visible += 1;
      }});

      categories.forEach((section) => {{
        const hasVisibleCard = Boolean(section.querySelector('.icon-card:not(.hidden)'));
        section.classList.toggle('hidden', !hasVisibleCard);
      }});

      visibleCount.textContent = String(visible);
    }}

    search.addEventListener('input', applyFilter);
  </script>
</body>
</html>
'''


def main() -> None:
    svg_files = collect_svg_files()
    OUTPUT.write_text(render_html(svg_files), encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(Path.cwd()) if OUTPUT.is_relative_to(Path.cwd()) else OUTPUT} with {len(svg_files)} icons")


if __name__ == "__main__":
    main()
