//! 图标注册表：id → [`IconDef`]，编译期内嵌 SVG 资产。

use crate::render::visual::NodeShape;

/// 图标放置策略。
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IconPlacement {
    /// 节点内侧，与标签横排（第一版实现目标）。
    Inside,
    /// 节点外侧角标（预留）。
    Outside,
    /// 已注册但不渲染。
    None,
}

/// 图标分类。
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IconCategory {
    People,
    Databases,
    Messaging,
    Services,
    Cloud,
    Generic,
}

/// 单个图标的元数据与内嵌资产。
#[derive(Debug, Clone, Copy)]
pub struct IconDef {
    pub id: &'static str,
    pub asset: &'static str,
    pub category: IconCategory,
    pub aliases: &'static [&'static str],

    pub placement: IconPlacement,
    pub scale: f64,
    pub optical_align_dy: f64,
    pub gap: f64,
    pub min_node_width: f64,
    pub min_node_height: f64,

    pub incompatible_shapes: &'static [NodeShape],
    pub label_keywords: &'static [&'static str],
    pub label_match_priority: u8,
}

const INCOMPATIBLE_CYLINDER: &[NodeShape] = &[NodeShape::Cylinder];
const INCOMPATIBLE_PERSON: &[NodeShape] = &[NodeShape::Person];
const INCOMPATIBLE_HEXAGON: &[NodeShape] = &[NodeShape::Hexagon];

static ICONS: &[IconDef] = &[
    // ── people ──
    IconDef {
        id: "user",
        asset: include_str!("assets/glyphs/people/user.svg"),
        category: IconCategory::People,
        aliases: &["users", "person"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 48.0,
        min_node_height: 32.0,
        incompatible_shapes: INCOMPATIBLE_PERSON,
        label_keywords: &["用户", "user"],
        label_match_priority: 5,
    },
    IconDef {
        id: "actor",
        asset: include_str!("assets/glyphs/people/actor.svg"),
        category: IconCategory::People,
        aliases: &["participant"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 48.0,
        min_node_height: 32.0,
        incompatible_shapes: INCOMPATIBLE_PERSON,
        label_keywords: &["actor", "参与者"],
        label_match_priority: 5,
    },
    IconDef {
        id: "admin",
        asset: include_str!("assets/glyphs/people/admin.svg"),
        category: IconCategory::People,
        aliases: &["administrator", "owner"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 52.0,
        min_node_height: 32.0,
        incompatible_shapes: INCOMPATIBLE_PERSON,
        label_keywords: &["admin", "administrator", "管理员"],
        label_match_priority: 8,
    },
    IconDef {
        id: "team",
        asset: include_str!("assets/glyphs/people/team.svg"),
        category: IconCategory::People,
        aliases: &["group", "org", "organization"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 56.0,
        min_node_height: 32.0,
        incompatible_shapes: INCOMPATIBLE_PERSON,
        label_keywords: &["team", "group", "团队", "组织"],
        label_match_priority: 6,
    },
    IconDef {
        id: "bot",
        asset: include_str!("assets/glyphs/people/bot.svg"),
        category: IconCategory::People,
        aliases: &["robot", "assistant", "agent"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 52.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["bot", "robot", "agent", "机器人", "助手"],
        label_match_priority: 8,
    },
    // ── databases（具体技术优先于类别 fallback）──
    IconDef {
        id: "mysql",
        asset: include_str!("assets/glyphs/databases/mysql.svg"),
        category: IconCategory::Databases,
        aliases: &["mariadb"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.5,
        gap: 4.0,
        min_node_width: 56.0,
        min_node_height: 32.0,
        incompatible_shapes: INCOMPATIBLE_CYLINDER,
        label_keywords: &["mysql"],
        label_match_priority: 10,
    },
    IconDef {
        id: "postgres",
        asset: include_str!("assets/glyphs/databases/postgres.svg"),
        category: IconCategory::Databases,
        aliases: &["postgresql", "pg"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 56.0,
        min_node_height: 32.0,
        incompatible_shapes: INCOMPATIBLE_CYLINDER,
        label_keywords: &["postgres", "postgresql"],
        label_match_priority: 10,
    },
    IconDef {
        id: "redis",
        asset: include_str!("assets/glyphs/databases/redis.svg"),
        category: IconCategory::Databases,
        aliases: &[],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 52.0,
        min_node_height: 32.0,
        incompatible_shapes: INCOMPATIBLE_CYLINDER,
        label_keywords: &["redis"],
        label_match_priority: 10,
    },
    IconDef {
        id: "mongodb",
        asset: include_str!("assets/glyphs/databases/mongodb.svg"),
        category: IconCategory::Databases,
        aliases: &["mongo"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 56.0,
        min_node_height: 32.0,
        incompatible_shapes: INCOMPATIBLE_CYLINDER,
        label_keywords: &["mongodb", "mongo"],
        label_match_priority: 10,
    },
    IconDef {
        id: "sqlite",
        asset: include_str!("assets/glyphs/databases/sqlite.svg"),
        category: IconCategory::Databases,
        aliases: &["sqlite3"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 56.0,
        min_node_height: 32.0,
        incompatible_shapes: INCOMPATIBLE_CYLINDER,
        label_keywords: &["sqlite", "sqlite3"],
        label_match_priority: 10,
    },
    IconDef {
        id: "elasticsearch",
        asset: include_str!("assets/glyphs/databases/elasticsearch.svg"),
        category: IconCategory::Databases,
        aliases: &["elastic", "es", "opensearch"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 60.0,
        min_node_height: 32.0,
        incompatible_shapes: INCOMPATIBLE_CYLINDER,
        label_keywords: &["elasticsearch", "elastic", "opensearch"],
        label_match_priority: 10,
    },
    IconDef {
        id: "oracle",
        asset: include_str!("assets/glyphs/databases/oracle.svg"),
        category: IconCategory::Databases,
        aliases: &["oracle_db", "oracledb"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 56.0,
        min_node_height: 32.0,
        incompatible_shapes: INCOMPATIBLE_CYLINDER,
        label_keywords: &["oracle", "oracle db"],
        label_match_priority: 10,
    },
    IconDef {
        id: "clickhouse",
        asset: include_str!("assets/glyphs/databases/clickhouse.svg"),
        category: IconCategory::Databases,
        aliases: &["ch", "olap_engine"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 60.0,
        min_node_height: 32.0,
        incompatible_shapes: INCOMPATIBLE_CYLINDER,
        label_keywords: &["clickhouse", "olap"],
        label_match_priority: 10,
    },
    IconDef {
        id: "data_warehouse",
        asset: include_str!("assets/glyphs/databases/data_warehouse.svg"),
        category: IconCategory::Databases,
        aliases: &["warehouse", "dwh", "olap", "hive", "clickhouse"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 60.0,
        min_node_height: 32.0,
        incompatible_shapes: INCOMPATIBLE_CYLINDER,
        label_keywords: &[
            "data warehouse",
            "warehouse",
            "olap",
            "hive",
            "clickhouse",
            "数仓",
            "数据仓库",
        ],
        label_match_priority: 9,
    },
    IconDef {
        id: "data_lake",
        asset: include_str!("assets/glyphs/databases/data_lake.svg"),
        category: IconCategory::Databases,
        aliases: &["lake", "lakehouse", "data_lakehouse"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 56.0,
        min_node_height: 32.0,
        incompatible_shapes: INCOMPATIBLE_CYLINDER,
        label_keywords: &["data lake", "lakehouse", "湖仓", "数据湖"],
        label_match_priority: 9,
    },
    IconDef {
        id: "database",
        asset: include_str!("assets/glyphs/databases/database.svg"),
        category: IconCategory::Databases,
        aliases: &["db", "sql"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 48.0,
        min_node_height: 32.0,
        incompatible_shapes: INCOMPATIBLE_CYLINDER,
        label_keywords: &[],
        label_match_priority: 0,
    },
    // ── messaging ──
    IconDef {
        id: "kafka",
        asset: include_str!("assets/glyphs/messaging/kafka.svg"),
        category: IconCategory::Messaging,
        aliases: &["apache_kafka"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 52.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["kafka"],
        label_match_priority: 10,
    },
    IconDef {
        id: "rabbitmq",
        asset: include_str!("assets/glyphs/messaging/rabbitmq.svg"),
        category: IconCategory::Messaging,
        aliases: &["rabbit_mq", "amqp"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: -0.5,
        gap: 4.0,
        min_node_width: 56.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["rabbitmq", "rabbit"],
        label_match_priority: 10,
    },
    IconDef {
        id: "eventbus",
        asset: include_str!("assets/glyphs/messaging/eventbus.svg"),
        category: IconCategory::Messaging,
        aliases: &["event_bus", "events", "pubsub", "pub_sub"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 56.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["eventbus", "event bus", "pubsub", "事件总线"],
        label_match_priority: 8,
    },
    IconDef {
        id: "webhook",
        asset: include_str!("assets/glyphs/messaging/webhook.svg"),
        category: IconCategory::Messaging,
        aliases: &["hook", "callback"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 56.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["webhook", "callback", "回调"],
        label_match_priority: 8,
    },
    // ── services ──
    IconDef {
        id: "service",
        asset: include_str!("assets/glyphs/services/service.svg"),
        category: IconCategory::Services,
        aliases: &["component", "module"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 48.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &[],
        label_match_priority: 0,
    },
    IconDef {
        id: "api",
        asset: include_str!("assets/glyphs/services/api.svg"),
        category: IconCategory::Services,
        aliases: &["rest", "http", "graphql", "grpc"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 48.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["api"],
        label_match_priority: 8,
    },
    IconDef {
        id: "gateway",
        asset: include_str!("assets/glyphs/services/gateway.svg"),
        category: IconCategory::Services,
        aliases: &["proxy", "ingress", "edge"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 52.0,
        min_node_height: 32.0,
        incompatible_shapes: INCOMPATIBLE_HEXAGON,
        label_keywords: &["gateway", "网关"],
        label_match_priority: 8,
    },
    IconDef {
        id: "cache",
        asset: include_str!("assets/glyphs/services/cache.svg"),
        category: IconCategory::Services,
        aliases: &["memcached"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 48.0,
        min_node_height: 32.0,
        incompatible_shapes: &[NodeShape::Diamond],
        label_keywords: &["cache", "缓存"],
        label_match_priority: 8,
    },
    IconDef {
        id: "queue",
        asset: include_str!("assets/glyphs/services/queue.svg"),
        category: IconCategory::Services,
        aliases: &["mq", "message_queue"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 48.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["queue", "队列"],
        label_match_priority: 8,
    },
    IconDef {
        id: "auth",
        asset: include_str!("assets/glyphs/services/auth.svg"),
        category: IconCategory::Services,
        aliases: &["iam", "oauth", "sso", "login"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 52.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["auth", "iam", "oauth", "sso", "login", "认证", "鉴权"],
        label_match_priority: 9,
    },
    IconDef {
        id: "worker",
        asset: include_str!("assets/glyphs/services/worker.svg"),
        category: IconCategory::Services,
        aliases: &["job", "consumer", "processor"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 52.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["worker", "job", "consumer", "任务", "消费者"],
        label_match_priority: 8,
    },
    IconDef {
        id: "function",
        asset: include_str!("assets/glyphs/services/function.svg"),
        category: IconCategory::Services,
        aliases: &["fn", "serverless"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 52.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["function", "serverless", "函数"],
        label_match_priority: 8,
    },
    IconDef {
        id: "search",
        asset: include_str!("assets/glyphs/services/search.svg"),
        category: IconCategory::Services,
        aliases: &["index", "query"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 48.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["search", "index", "搜索", "检索"],
        label_match_priority: 8,
    },
    IconDef {
        id: "storage",
        asset: include_str!("assets/glyphs/services/storage.svg"),
        category: IconCategory::Services,
        aliases: &["blob", "object_storage", "bucket"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 52.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["storage", "bucket", "blob", "存储", "对象存储"],
        label_match_priority: 8,
    },
    IconDef {
        id: "cron",
        asset: include_str!("assets/glyphs/services/cron.svg"),
        category: IconCategory::Services,
        aliases: &["scheduler", "schedule", "timer"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 48.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["cron", "scheduler", "schedule", "timer", "定时", "调度"],
        label_match_priority: 8,
    },
    IconDef {
        id: "monitor",
        asset: include_str!("assets/glyphs/services/monitor.svg"),
        category: IconCategory::Services,
        aliases: &["metrics", "observability", "alert"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 52.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &[
            "monitor",
            "metrics",
            "alert",
            "observability",
            "监控",
            "告警",
        ],
        label_match_priority: 8,
    },
    IconDef {
        id: "service_mesh",
        asset: include_str!("assets/glyphs/services/service_mesh.svg"),
        category: IconCategory::Services,
        aliases: &["mesh", "istio", "linkerd"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 60.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["service mesh", "mesh", "istio", "linkerd", "服务网格"],
        label_match_priority: 9,
    },
    IconDef {
        id: "config",
        asset: include_str!("assets/glyphs/services/config.svg"),
        category: IconCategory::Services,
        aliases: &["configuration", "configmap", "settings"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 52.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["config", "configuration", "configmap", "配置"],
        label_match_priority: 8,
    },
    IconDef {
        id: "secret",
        asset: include_str!("assets/glyphs/services/secret.svg"),
        category: IconCategory::Services,
        aliases: &["secrets", "key", "cert", "certificate", "cert_manager"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 52.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["secret", "secrets", "cert", "certificate", "密钥", "证书"],
        label_match_priority: 9,
    },
    IconDef {
        id: "ci",
        asset: include_str!("assets/glyphs/services/ci.svg"),
        category: IconCategory::Services,
        aliases: &[
            "pipeline",
            "build",
            "github_actions",
            "gitlab_ci",
            "argo",
            "argo_cd",
        ],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 52.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["ci", "pipeline", "build", "argo", "流水线", "构建"],
        label_match_priority: 8,
    },
    IconDef {
        id: "registry",
        asset: include_str!("assets/glyphs/services/registry.svg"),
        category: IconCategory::Services,
        aliases: &[
            "image_registry",
            "container_registry",
            "harbor",
            "ecr",
            "acr",
            "gcr",
        ],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 56.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["registry", "image registry", "harbor", "镜像仓库"],
        label_match_priority: 9,
    },
    IconDef {
        id: "spark",
        asset: include_str!("assets/glyphs/services/spark.svg"),
        category: IconCategory::Services,
        aliases: &["apache_spark", "batch_compute"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 52.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["spark", "apache spark", "批处理"],
        label_match_priority: 10,
    },
    IconDef {
        id: "flink",
        asset: include_str!("assets/glyphs/services/flink.svg"),
        category: IconCategory::Services,
        aliases: &["apache_flink", "stream_compute"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 52.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["flink", "apache flink", "stream", "流计算"],
        label_match_priority: 10,
    },
    IconDef {
        id: "argo",
        asset: include_str!("assets/glyphs/services/argo.svg"),
        category: IconCategory::Services,
        aliases: &["argocd", "argo_cd", "argo_rollouts", "rollouts"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 52.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["argo", "argocd", "argo cd", "argo rollouts"],
        label_match_priority: 10,
    },
    IconDef {
        id: "jenkins",
        asset: include_str!("assets/glyphs/services/jenkins.svg"),
        category: IconCategory::Services,
        aliases: &["jenkins_ci"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 52.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["jenkins"],
        label_match_priority: 10,
    },
    IconDef {
        id: "prometheus",
        asset: include_str!("assets/glyphs/services/prometheus.svg"),
        category: IconCategory::Services,
        aliases: &["prom", "metrics_store"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 56.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["prometheus"],
        label_match_priority: 10,
    },
    IconDef {
        id: "grafana",
        asset: include_str!("assets/glyphs/services/grafana.svg"),
        category: IconCategory::Services,
        aliases: &["dashboard", "dashboards"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 56.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["grafana", "dashboard", "看板", "大屏"],
        label_match_priority: 10,
    },
    IconDef {
        id: "logs",
        asset: include_str!("assets/glyphs/services/logs.svg"),
        category: IconCategory::Services,
        aliases: &["log", "loki", "audit_log", "audit_logs"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 52.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["logs", "log", "loki", "audit log", "日志", "审计"],
        label_match_priority: 9,
    },
    IconDef {
        id: "traces",
        asset: include_str!("assets/glyphs/services/traces.svg"),
        category: IconCategory::Services,
        aliases: &["trace", "tracing", "tempo", "jaeger", "span"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 52.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &[
            "traces", "trace", "tracing", "tempo", "jaeger", "链路", "追踪",
        ],
        label_match_priority: 9,
    },
    IconDef {
        id: "cdc",
        asset: include_str!("assets/glyphs/services/cdc.svg"),
        category: IconCategory::Services,
        aliases: &["change_data_capture", "connector", "debezium", "binlog"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 52.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["cdc", "connector", "binlog", "debezium", "数据采集"],
        label_match_priority: 9,
    },
    IconDef {
        id: "bi",
        asset: include_str!("assets/glyphs/services/bi.svg"),
        category: IconCategory::Services,
        aliases: &["business_intelligence", "report", "reporting"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 48.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["bi", "business intelligence", "report", "报表", "可视化"],
        label_match_priority: 8,
    },
    IconDef {
        id: "ml_model",
        asset: include_str!("assets/glyphs/services/ml_model.svg"),
        category: IconCategory::Services,
        aliases: &["model", "model_scoring", "ai_model", "ml"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 56.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["model", "model scoring", "ml", "模型", "评分"],
        label_match_priority: 8,
    },
    IconDef {
        id: "payment",
        asset: include_str!("assets/glyphs/services/payment.svg"),
        category: IconCategory::Services,
        aliases: &["pay", "checkout", "cashier", "card"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 52.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["payment", "pay", "checkout", "cashier", "支付", "收银台"],
        label_match_priority: 8,
    },
    IconDef {
        id: "ledger",
        asset: include_str!("assets/glyphs/services/ledger.svg"),
        category: IconCategory::Services,
        aliases: &["accounting", "book", "journal"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 52.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["ledger", "accounting", "账本", "账务", "记账"],
        label_match_priority: 8,
    },
    IconDef {
        id: "notification",
        asset: include_str!("assets/glyphs/services/notification.svg"),
        category: IconCategory::Services,
        aliases: &["notify", "alerting", "sms", "email", "message"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 52.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["notification", "notify", "alerting", "sms", "通知", "短信"],
        label_match_priority: 8,
    },
    IconDef {
        id: "slack",
        asset: include_str!("assets/glyphs/services/slack.svg"),
        category: IconCategory::Services,
        aliases: &["chatops", "chat", "messaging_app"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 52.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["slack", "chatops"],
        label_match_priority: 10,
    },
    IconDef {
        id: "jira",
        asset: include_str!("assets/glyphs/services/jira.svg"),
        category: IconCategory::Services,
        aliases: &["issue_tracker", "ticket", "tickets"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 48.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["jira", "ticket", "issue", "工单"],
        label_match_priority: 9,
    },
    IconDef {
        id: "confluence",
        asset: include_str!("assets/glyphs/services/confluence.svg"),
        category: IconCategory::Services,
        aliases: &["wiki", "knowledge_base", "docs"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 56.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &[
            "confluence",
            "wiki",
            "knowledge base",
            "docs",
            "知识库",
            "文档",
        ],
        label_match_priority: 9,
    },
    IconDef {
        id: "sentry",
        asset: include_str!("assets/glyphs/services/sentry.svg"),
        category: IconCategory::Services,
        aliases: &["error_tracking", "errors"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 52.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["sentry", "error tracking", "errors", "异常"],
        label_match_priority: 10,
    },
    IconDef {
        id: "datadog",
        asset: include_str!("assets/glyphs/services/datadog.svg"),
        category: IconCategory::Services,
        aliases: &["dd", "datadog_monitoring"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 52.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["datadog"],
        label_match_priority: 10,
    },
    // ── cloud ──
    IconDef {
        id: "k8s",
        asset: include_str!("assets/glyphs/cloud/k8s.svg"),
        category: IconCategory::Cloud,
        aliases: &["kubernetes"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 52.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["kubernetes", "k8s"],
        label_match_priority: 10,
    },
    IconDef {
        id: "s3",
        asset: include_str!("assets/glyphs/cloud/s3.svg"),
        category: IconCategory::Cloud,
        aliases: &["bucket", "object_store", "object_storage"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 52.0,
        min_node_height: 32.0,
        incompatible_shapes: INCOMPATIBLE_CYLINDER,
        label_keywords: &["s3", "bucket"],
        label_match_priority: 10,
    },
    IconDef {
        id: "lambda",
        asset: include_str!("assets/glyphs/cloud/lambda.svg"),
        category: IconCategory::Cloud,
        aliases: &["aws_lambda", "cloud_function"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 52.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["lambda", "cloud function"],
        label_match_priority: 10,
    },
    IconDef {
        id: "docker",
        asset: include_str!("assets/glyphs/cloud/docker.svg"),
        category: IconCategory::Cloud,
        aliases: &["container", "containers"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 56.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["docker", "container", "容器"],
        label_match_priority: 10,
    },
    IconDef {
        id: "cdn",
        asset: include_str!("assets/glyphs/cloud/cdn.svg"),
        category: IconCategory::Cloud,
        aliases: &["edge_network"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 52.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["cdn", "edge", "边缘"],
        label_match_priority: 8,
    },
    IconDef {
        id: "load_balancer",
        asset: include_str!("assets/glyphs/cloud/load_balancer.svg"),
        category: IconCategory::Cloud,
        aliases: &["lb", "elb", "alb", "loadbalancer"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 60.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["load balancer", "loadbalancer", "负载均衡"],
        label_match_priority: 8,
    },
    IconDef {
        id: "dns",
        asset: include_str!("assets/glyphs/cloud/dns.svg"),
        category: IconCategory::Cloud,
        aliases: &["domain", "route53"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 48.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["dns", "domain", "域名"],
        label_match_priority: 9,
    },
    IconDef {
        id: "waf",
        asset: include_str!("assets/glyphs/cloud/waf.svg"),
        category: IconCategory::Cloud,
        aliases: &["web_application_firewall", "firewall"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 48.0,
        min_node_height: 32.0,
        incompatible_shapes: INCOMPATIBLE_HEXAGON,
        label_keywords: &["waf", "firewall", "防火墙"],
        label_match_priority: 9,
    },
    IconDef {
        id: "ingress",
        asset: include_str!("assets/glyphs/cloud/ingress.svg"),
        category: IconCategory::Cloud,
        aliases: &["ingress_gateway", "ingress_controller", "nginx_ingress"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 56.0,
        min_node_height: 32.0,
        incompatible_shapes: INCOMPATIBLE_HEXAGON,
        label_keywords: &["ingress", "nginx ingress"],
        label_match_priority: 9,
    },
    IconDef {
        id: "nginx",
        asset: include_str!("assets/glyphs/cloud/nginx.svg"),
        category: IconCategory::Cloud,
        aliases: &["nginx_ingress", "nginx_proxy"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 52.0,
        min_node_height: 32.0,
        incompatible_shapes: INCOMPATIBLE_HEXAGON,
        label_keywords: &["nginx"],
        label_match_priority: 10,
    },
    IconDef {
        id: "minio",
        asset: include_str!("assets/glyphs/cloud/minio.svg"),
        category: IconCategory::Cloud,
        aliases: &["min_io", "s3_compatible"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 52.0,
        min_node_height: 32.0,
        incompatible_shapes: INCOMPATIBLE_CYLINDER,
        label_keywords: &["minio", "min io"],
        label_match_priority: 10,
    },
    IconDef {
        id: "pod",
        asset: include_str!("assets/glyphs/cloud/pod.svg"),
        category: IconCategory::Cloud,
        aliases: &["pods", "replicaset", "replica_set"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 48.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["pod", "pods", "replicaset"],
        label_match_priority: 9,
    },
    IconDef {
        id: "node",
        asset: include_str!("assets/glyphs/cloud/node.svg"),
        category: IconCategory::Cloud,
        aliases: &["nodes", "k8s_node", "worker_node", "kubelet"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 48.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["node", "kubelet", "节点"],
        label_match_priority: 9,
    },
    IconDef {
        id: "deployment",
        asset: include_str!("assets/glyphs/cloud/deployment.svg"),
        category: IconCategory::Cloud,
        aliases: &[
            "deploy",
            "workload",
            "workloads",
            "rollout",
            "argo_rollouts",
        ],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 60.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &[
            "deployment",
            "deploy",
            "workload",
            "rollout",
            "发布",
            "工作负载",
        ],
        label_match_priority: 9,
    },
    // ── generic ──
    IconDef {
        id: "server",
        asset: include_str!("assets/glyphs/generic/server.svg"),
        category: IconCategory::Generic,
        aliases: &["svc"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 48.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &[],
        label_match_priority: 0,
    },
    IconDef {
        id: "external",
        asset: include_str!("assets/glyphs/generic/external.svg"),
        category: IconCategory::Generic,
        aliases: &["third_party", "3rd_party"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 48.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["external", "第三方"],
        label_match_priority: 5,
    },
    IconDef {
        id: "browser",
        asset: include_str!("assets/glyphs/generic/browser.svg"),
        category: IconCategory::Generic,
        aliases: &["web", "frontend"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 52.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["browser", "web", "frontend", "浏览器"],
        label_match_priority: 6,
    },
    IconDef {
        id: "mobile",
        asset: include_str!("assets/glyphs/generic/mobile.svg"),
        category: IconCategory::Generic,
        aliases: &["app", "ios", "android"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 48.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["mobile", "ios", "android", "app", "移动端"],
        label_match_priority: 6,
    },
    IconDef {
        id: "desktop",
        asset: include_str!("assets/glyphs/generic/desktop.svg"),
        category: IconCategory::Generic,
        aliases: &["client"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 52.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["desktop", "client", "桌面端", "客户端"],
        label_match_priority: 6,
    },
    IconDef {
        id: "file",
        asset: include_str!("assets/glyphs/generic/file.svg"),
        category: IconCategory::Generic,
        aliases: &["document", "doc"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 48.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["file", "document", "文件", "文档"],
        label_match_priority: 5,
    },
    IconDef {
        id: "repo",
        asset: include_str!("assets/glyphs/generic/repo.svg"),
        category: IconCategory::Generic,
        aliases: &["repository", "git", "code_repo", "source_code"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 52.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["repo", "repository", "git", "代码仓库", "源码"],
        label_match_priority: 8,
    },
    IconDef {
        id: "pr",
        asset: include_str!("assets/glyphs/generic/pr.svg"),
        category: IconCategory::Generic,
        aliases: &["pull_request", "merge_request", "mr", "review"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 48.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["pull request", "merge request", "pr", "review", "代码评审"],
        label_match_priority: 8,
    },
    IconDef {
        id: "github",
        asset: include_str!("assets/glyphs/generic/github.svg"),
        category: IconCategory::Generic,
        aliases: &["gh", "github_actions"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 52.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["github", "github actions"],
        label_match_priority: 10,
    },
    IconDef {
        id: "gitlab",
        asset: include_str!("assets/glyphs/generic/gitlab.svg"),
        category: IconCategory::Generic,
        aliases: &["gitlab_ci"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 52.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["gitlab", "gitlab ci"],
        label_match_priority: 10,
    },
    IconDef {
        id: "folder",
        asset: include_str!("assets/glyphs/generic/folder.svg"),
        category: IconCategory::Generic,
        aliases: &["directory", "dir"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 52.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["folder", "directory", "目录", "文件夹"],
        label_match_priority: 5,
    },
    IconDef {
        id: "lock",
        asset: include_str!("assets/glyphs/generic/lock.svg"),
        category: IconCategory::Generic,
        aliases: &["secure", "security"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 48.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["secure", "security", "lock", "安全", "加密"],
        label_match_priority: 6,
    },
    IconDef {
        id: "globe",
        asset: include_str!("assets/glyphs/generic/globe.svg"),
        category: IconCategory::Generic,
        aliases: &["internet", "world"],
        placement: IconPlacement::Inside,
        scale: 1.0,
        optical_align_dy: 0.0,
        gap: 4.0,
        min_node_width: 52.0,
        min_node_height: 32.0,
        incompatible_shapes: &[],
        label_keywords: &["internet", "global", "world", "公网", "全球"],
        label_match_priority: 5,
    },
];

/// 全部已注册图标。
pub fn all_icons() -> &'static [IconDef] {
    ICONS
}

/// 按 id 查找（精确匹配，调用方应传入已规范化的 key）。
pub fn icon_by_id(id: &str) -> Option<&'static IconDef> {
    ICONS.iter().find(|icon| icon.id == id)
}

/// 按 id 或别名查找。
pub fn icon_by_key(key: &str) -> Option<&'static IconDef> {
    let key = normalize_key(key);
    if key.is_empty() || key == "none" {
        return None;
    }
    icon_by_id(&key).or_else(|| {
        ICONS
            .iter()
            .find(|icon| icon.aliases.iter().any(|alias| normalize_key(alias) == key))
    })
}

/// 规范化图标 key：小写、`-` → `_`、去首尾空白。
pub fn normalize_key(value: &str) -> String {
    value.trim().to_ascii_lowercase().replace('-', "_")
}

/// 已知图标 id 列表（测试与校验用）。
pub fn known_icon_ids() -> impl Iterator<Item = &'static str> {
    ICONS.iter().map(|icon| icon.id)
}
