//! 全局 semantic 词表与 semantic → icon 集中映射。
//!
//! 词表由 icon catalog 的 id、aliases 及历史 fallback 语义合并生成（方案 A）。

use super::catalog;

/// semantic 键 → icon id（均为小写 snake_case）。
static SEMANTIC_MAPPINGS: &[(&str, &str)] = &[
    ("3rd_party", "external"),
    ("accounting", "ledger"),
    ("acr", "registry"),
    ("actor", "actor"),
    ("admin", "admin"),
    ("administrator", "admin"),
    ("agent", "bot"),
    ("ai_model", "ml_model"),
    ("alb", "load_balancer"),
    ("alert", "monitor"),
    ("alerting", "notification"),
    ("amqp", "rabbitmq"),
    ("android", "mobile"),
    ("apache_flink", "flink"),
    ("apache_kafka", "kafka"),
    ("apache_spark", "spark"),
    ("api", "api"),
    ("app", "mobile"),
    ("argo", "ci"),
    ("argo_cd", "ci"),
    ("argo_rollouts", "argo"),
    ("argocd", "argo"),
    ("assistant", "bot"),
    ("audit_log", "logs"),
    ("audit_logs", "logs"),
    ("auth", "auth"),
    ("authentication", "auth"),
    ("authorization", "auth"),
    ("aws_lambda", "lambda"),
    ("backend", "server"),
    ("batch_compute", "spark"),
    ("bi", "bi"),
    ("binlog", "cdc"),
    ("blob", "storage"),
    ("book", "ledger"),
    ("bot", "bot"),
    ("browser", "browser"),
    ("bucket", "storage"),
    ("build", "ci"),
    ("business_intelligence", "bi"),
    ("cache", "cache"),
    ("callback", "webhook"),
    ("card", "payment"),
    ("cashier", "payment"),
    ("cdc", "cdc"),
    ("cdn", "cdn"),
    ("cert", "secret"),
    ("cert_manager", "secret"),
    ("certificate", "secret"),
    ("ch", "clickhouse"),
    ("change_data_capture", "cdc"),
    ("chat", "slack"),
    ("chatops", "slack"),
    ("checkout", "payment"),
    ("ci", "ci"),
    ("clickhouse", "clickhouse"),
    ("client", "user"),
    ("cloud_function", "lambda"),
    ("code_repo", "repo"),
    ("component", "service"),
    ("config", "config"),
    ("configmap", "config"),
    ("configuration", "config"),
    ("confluence", "confluence"),
    ("connector", "cdc"),
    ("consumer", "worker"),
    ("container", "docker"),
    ("container_registry", "registry"),
    ("containers", "docker"),
    ("cron", "cron"),
    ("dashboard", "grafana"),
    ("dashboards", "grafana"),
    ("data_lake", "data_lake"),
    ("data_lakehouse", "data_lake"),
    ("data_warehouse", "data_warehouse"),
    ("database", "database"),
    ("datadog", "datadog"),
    ("datadog_monitoring", "datadog"),
    ("db", "database"),
    ("dd", "datadog"),
    ("debezium", "cdc"),
    ("deploy", "deployment"),
    ("deployment", "deployment"),
    ("desktop", "desktop"),
    ("dir", "folder"),
    ("directory", "folder"),
    ("dns", "dns"),
    ("doc", "file"),
    ("docker", "docker"),
    ("docs", "confluence"),
    ("document", "file"),
    ("domain", "dns"),
    ("dwh", "data_warehouse"),
    ("ecr", "registry"),
    ("edge", "gateway"),
    ("edge_network", "cdn"),
    ("elastic", "elasticsearch"),
    ("elasticsearch", "elasticsearch"),
    ("elb", "load_balancer"),
    ("email", "notification"),
    ("error_tracking", "sentry"),
    ("errors", "sentry"),
    ("es", "elasticsearch"),
    ("event_bus", "eventbus"),
    ("eventbus", "eventbus"),
    ("events", "eventbus"),
    ("external", "external"),
    ("file", "file"),
    ("firewall", "waf"),
    ("flink", "flink"),
    ("fn", "function"),
    ("folder", "folder"),
    ("frontend", "user"),
    ("function", "function"),
    ("gateway", "gateway"),
    ("gcr", "registry"),
    ("gh", "github"),
    ("git", "repo"),
    ("github", "github"),
    ("github_actions", "ci"),
    ("gitlab", "gitlab"),
    ("gitlab_ci", "ci"),
    ("globe", "globe"),
    ("grafana", "grafana"),
    ("graphql", "api"),
    ("group", "team"),
    ("grpc", "api"),
    ("harbor", "registry"),
    ("hive", "data_warehouse"),
    ("hook", "webhook"),
    ("http", "api"),
    ("iam", "auth"),
    ("image_registry", "registry"),
    ("index", "search"),
    ("ingress", "gateway"),
    ("ingress_controller", "ingress"),
    ("ingress_gateway", "ingress"),
    ("internet", "globe"),
    ("ios", "mobile"),
    ("issue", "jira"),
    ("issue_tracker", "jira"),
    ("istio", "service_mesh"),
    ("jaeger", "traces"),
    ("jenkins", "jenkins"),
    ("jenkins_ci", "jenkins"),
    ("jira", "jira"),
    ("job", "worker"),
    ("journal", "ledger"),
    ("k8s", "k8s"),
    ("k8s_node", "node"),
    ("kafka", "kafka"),
    ("key", "secret"),
    ("knowledge_base", "confluence"),
    ("kubelet", "node"),
    ("kubernetes", "k8s"),
    ("lake", "data_lake"),
    ("lakehouse", "data_lake"),
    ("lambda", "lambda"),
    ("lb", "load_balancer"),
    ("ledger", "ledger"),
    ("linkerd", "service_mesh"),
    ("load_balancer", "load_balancer"),
    ("loadbalancer", "load_balancer"),
    ("lock", "lock"),
    ("log", "logs"),
    ("login", "auth"),
    ("logs", "logs"),
    ("loki", "logs"),
    ("mariadb", "mysql"),
    ("memcached", "cache"),
    ("merge_request", "pr"),
    ("mesh", "service_mesh"),
    ("message", "notification"),
    ("message_queue", "queue"),
    ("messaging_app", "slack"),
    ("metrics", "monitor"),
    ("metrics_store", "prometheus"),
    ("min_io", "minio"),
    ("minio", "minio"),
    ("ml", "ml_model"),
    ("ml_model", "ml_model"),
    ("mobile", "mobile"),
    ("model", "ml_model"),
    ("model_scoring", "ml_model"),
    ("module", "service"),
    ("mongo", "mongodb"),
    ("mongodb", "mongodb"),
    ("monitor", "monitor"),
    ("mq", "queue"),
    ("mr", "pr"),
    ("mysql", "mysql"),
    ("nginx", "nginx"),
    ("nginx_ingress", "ingress"),
    ("nginx_proxy", "nginx"),
    ("node", "node"),
    ("nodes", "node"),
    ("notification", "notification"),
    ("notify", "notification"),
    ("oauth", "auth"),
    ("object_storage", "storage"),
    ("object_store", "s3"),
    ("observability", "monitor"),
    ("olap", "data_warehouse"),
    ("olap_engine", "clickhouse"),
    ("opensearch", "elasticsearch"),
    ("oracle", "oracle"),
    ("oracle_db", "oracle"),
    ("oracledb", "oracle"),
    ("org", "team"),
    ("organization", "team"),
    ("owner", "admin"),
    ("participant", "actor"),
    ("pay", "payment"),
    ("payment", "payment"),
    ("person", "user"),
    ("pg", "postgres"),
    ("pipeline", "ci"),
    ("pod", "pod"),
    ("pods", "pod"),
    ("postgres", "postgres"),
    ("postgresql", "postgres"),
    ("pr", "pr"),
    ("processor", "worker"),
    ("prom", "prometheus"),
    ("prometheus", "prometheus"),
    ("proxy", "gateway"),
    ("pub_sub", "eventbus"),
    ("pubsub", "eventbus"),
    ("pull_request", "pr"),
    ("query", "search"),
    ("queue", "queue"),
    ("rabbit_mq", "rabbitmq"),
    ("rabbitmq", "rabbitmq"),
    ("redis", "redis"),
    ("registry", "registry"),
    ("replica_set", "pod"),
    ("replicaset", "pod"),
    ("repo", "repo"),
    ("report", "bi"),
    ("reporting", "bi"),
    ("repository", "repo"),
    ("rest", "api"),
    ("review", "pr"),
    ("robot", "bot"),
    ("rollout", "deployment"),
    ("rollouts", "argo"),
    ("route53", "dns"),
    ("s3", "s3"),
    ("s3_compatible", "minio"),
    ("schedule", "cron"),
    ("scheduler", "cron"),
    ("search", "search"),
    ("secret", "secret"),
    ("secrets", "secret"),
    ("secure", "lock"),
    ("security", "lock"),
    ("sentry", "sentry"),
    ("server", "server"),
    ("serverless", "function"),
    ("service", "service"),
    ("service_mesh", "service_mesh"),
    ("settings", "config"),
    ("slack", "slack"),
    ("sms", "notification"),
    ("source_code", "repo"),
    ("span", "traces"),
    ("spark", "spark"),
    ("sql", "database"),
    ("sqlite", "sqlite"),
    ("sqlite3", "sqlite"),
    ("sso", "auth"),
    ("storage", "storage"),
    ("stream_compute", "flink"),
    ("svc", "server"),
    ("team", "team"),
    ("tempo", "traces"),
    ("third_party", "external"),
    ("ticket", "jira"),
    ("tickets", "jira"),
    ("timer", "cron"),
    ("trace", "traces"),
    ("traces", "traces"),
    ("tracing", "traces"),
    ("user", "user"),
    ("users", "user"),
    ("waf", "waf"),
    ("warehouse", "data_warehouse"),
    ("web", "browser"),
    ("web_application_firewall", "waf"),
    ("webhook", "webhook"),
    ("wiki", "confluence"),
    ("worker", "worker"),
    ("worker_node", "node"),
    ("workload", "deployment"),
    ("workloads", "deployment"),
    ("world", "globe"),
];

/// 规范化 semantic 键（与 icon catalog 一致）。
pub fn normalize_semantic(value: &str) -> String {
    catalog::normalize_key(value)
}

/// semantic 是否在全局封闭词表中。
pub fn is_known_semantic(value: &str) -> bool {
    let key = normalize_semantic(value);
    if key.is_empty() {
        return false;
    }
    SEMANTIC_MAPPINGS
        .binary_search_by_key(&key.as_str(), |(semantic, _)| semantic)
        .is_ok()
}

/// 将 semantic 解析为 icon id；词表命中但无图标映射时返回 `None`（当前词表项均映射到图标）。
pub fn semantic_to_icon_id(value: &str) -> Option<&'static str> {
    let key = normalize_semantic(value);
    if key.is_empty() {
        return None;
    }
    SEMANTIC_MAPPINGS
        .binary_search_by_key(&key.as_str(), |(semantic, _)| semantic)
        .ok()
        .map(|idx| SEMANTIC_MAPPINGS[idx].1)
}

/// 已知 semantic 词表（测试与文档用）。
pub fn known_semantic_count() -> usize {
    SEMANTIC_MAPPINGS.len()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn mappings_are_sorted_for_binary_search() {
        for window in SEMANTIC_MAPPINGS.windows(2) {
            assert!(window[0].0 <= window[1].0, "{} > {}", window[0].0, window[1].0);
        }
    }

    #[test]
    fn resolves_mysql_and_frontend() {
        assert_eq!(semantic_to_icon_id("mysql"), Some("mysql"));
        assert_eq!(semantic_to_icon_id("MySQL"), Some("mysql"));
        assert_eq!(semantic_to_icon_id("frontend"), Some("user"));
        assert!(is_known_semantic("kafka"));
        assert!(!is_known_semantic("not_a_real_semantic"));
    }
}
